SELECT 
ITM.ITEMCODE,
ITM.ITEMNAME,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MINPRICE,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MAXPRICE,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS AVGPRICE,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOTALAMOOUNT

FROM 
ITEMS ITM 

ORDER BY ITEMCODE

