SELECT CONVERT(DATE,DATE_) AS DATE2, * 
FROM SALES WHERE CITY='ANKARA' AND DATE='2019-01-01'
ORDER BY DATE_


UPDATE SALES SET DATE2=CONVERT(DATE,DATE_)


SELECT CITY,DATE2,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES WHERE CITY='ANKARA'
GROUP BY CITY,DATE2
ORDER BY CITY,DATE2


