SELECT CT.CITY , COUNT(U.ID) AS NumberOfUser
FROM USERS U 
JOIN  ADRESS A ON U.ID = A.USERID
JOIN COUNTRIES C ON C.ID = A.COUNTRYID
JOIN CITIES CT ON CT.ID = A.CITYID
JOIN TOWN T ON T.ID = A.TOWNID
GROUP BY CT.CITY

