--ASCII , CHAR
SELECT ASCII ('A') --65
SELECT CHAR (65)   --A
SELECT ASCII(CHAR(65)) --65
SELECT  CHAR(ASCII('A')) --A

--SUBSTRING
SELECT SUBSTRING('HELLO WORLD',1,5)
SELECT * FROM USERS WHERE USERNAME_ LIKE 'O%'
SELECT * FROM USERS WHERE SUBSTRING(USERNAME_,1,1)='O'
SELECT * FROM USERS WHERE SUBSTRING(USERNAME_,LEN(USERNAME_),1)='O'

--CHARINDEX
SELECT CHARINDEX('L','HELLO WORLD',1)

--CONCAT
SELECT 'LEARN'+' ' + 'SQL'
SELECT CONCAT('LEARN',' ' , 'SQL')
SELECT CONCAT_WS(' ','HELLO','LEARN','SQL')

SELECT 
	USERNAME_ + ' '+ PASSWORD_ + ' '+NAMESURNAME,
* FROM USERS
------------
SELECT 
	CONCAT(USERNAME_ , ' ', PASSWORD_ , ' ', NAMESURNAME),
* FROM USERS
------------
SELECT 
	CONCAT_WS(' ',USERNAME_ , PASSWORD_ , NAMESURNAME),
* FROM USERS


--FORMAT
SELECT FORMAT(GETDATE(),'d','en-us')
SELECT FORMAT(GETDATE(),'D','en-us')

--LEFT,RIGHT,LEN
SELECT LEFT('HELLO',2)
SELECT RIGHT('HELLO',2)
SELECT LEN('HELLO')


SELECT LEFT('LEARN SQL',5)
SELECT LEFT('LEARN SQL',CHARINDEX(' ' , 'LEARN SQL'))

SELECT RIGHT('LEARN SQL',3)
SELECT RIGHT('LEARN SQL',LEN('LEARN SQL')- CHARINDEX(' ' , 'LEARN SQL'))

SELECT LEFT('LEARN SQL',CHARINDEX(' ' , 'LEARN SQL')),RIGHT('LEARN SQL',LEN('LEARN SQL')- CHARINDEX(' ' , 'LEARN SQL'))
------------
SELECT 
LEFT(NAMESURNAME,CHARINDEX(' ' , NAMESURNAME)) AS NAME_,
RIGHT(NAMESURNAME,LEN(NAMESURNAME)- CHARINDEX(' ' , NAMESURNAME)) AS SURNAME
FROM USERS

--TRIM(DELETING SPACES),LTRIM(LEFT),RTRIM(RIGHT)
SELECT TRIM('  HELLO WORLD ')
SELECT LTRIM('  HELLO WORLD ')
SELECT RTRIM('   HELLO WORLD    ')
SELECT RTRIM(LTRIM('   HELLO WORLD    '))


--LOWER,UPPER,REVERSE,REPLICATE
SELECT LOWER('HELLO WORLD')
SELECT UPPER('Hello')
SELECT REVERSE('Hello')
SELECT REPLICATE('0',3)

--REPLACE
SELECT 'HELLO WORLD'
SELECT REPLACE('HELLO WORLD','HELLO','HI')

