SELECT FICHENO,COUNT(*) AS AMOUNTOFPRODUCT
FROM SALES
WHERE MONTHNAME_='01.January' AND CITY='İSTANBUL'
GROUP BY FICHENO


SELECT CITY,COUNT(DISTINCT FICHENO) AS TOTALFISHE,COUNT(*) AS AMOUNTOFPRODUCT
FROM SALES
WHERE MONTHNAME_='01.January' 
GROUP BY CITY
ORDER BY CITY

SELECT CITY,
COUNT(DISTINCT CUSTOMERNAME) AS UNIQUECUSTOMER,
COUNT(DISTINCT FICHENO) AS TOTALFISHE,
COUNT(*) AS ITEMCOUNT
FROM SALES
WHERE MONTHNAME_='01.January' 
GROUP BY CITY
ORDER BY CITY