SELECT 
CITY,
MIN(TOTALPRICE) AS MINPRICE,
MAX(TOTALPRICE) AS MAXPRICE,
SUM(TOTALPRICE) AS TOTALPRICE, 
AVG(TOTALPRICE) AS AVGPRICE,
COUNT(ID)       AS ROWCOUNT_
FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) ASC


SELECT 
CITY,
SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC


SELECT TOP 10
CITY,
SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC


