CREATE TABLE ITEMS(
ID INT IDENTITY (1,1),
ITEMCODE VARCHAR(50),
ITEMNAME VARCHAR(100),
UNITPRICE FLOAT,
CATEGORY1 VARCHAR(50),
CATEGORY2 VARCHAR(50),
CATEGORY3 VARCHAR(50),
CATEGORY4 VARCHAR(50),
BRAND VARCHAR(50),
CONSTRAINT  PK_ITEMS PRIMARY KEY CLUSTERED(ID ASC))
