CREATE TABLE USERS(
ID INT IDENTITY (1,1),
USERNAME_ VARCHAR(50),
PASSWORD_ VARCHAR(50),
NAMESURNAME VARCHAR(100),
EMAIL VARCHAR(100),
GENDER VARCHAR(1),
BIRTHDATE DATE,
CREATEDATE DATETIME,
TELNR1 VARCHAR(15),
TELNR2 VARCHAR(15),
CONSTRAINT  PK_USERS PRIMARY KEY CLUSTERED([ID] ASC ));

