CREATE TABLE ORDERS(
ID INT IDENTITY (1,1),
USERID INT  ,
DATE_ DATETIME,
TOTALPRICE FLOAT,
STATUS_ TINYINT,
ADDRESSID INT
CONSTRAINT  PK_ORDERS PRIMARY KEY CLUSTERED([ID] ASC ))
CREATE TABLE ORDERSDETAILS(
ID INT IDENTITY (1,1),
ORDERID INT  ,
ITEMID INT,
AMOUNT INT,
UNITPRICE FLOAT,
LINETOTAL FLOAT
CONSTRAINT  PK_ORDERSDETAILS PRIMARY KEY CLUSTERED([ID] ASC ))
