CREATE TABLE ADDRESS(
ID INT IDENTITY(1,1) ,
USERID INT ,
COUNTRYID TINYINT,
CITYID SMALLINT,
TOWNID INT ,
DISTRICT INT ,
POSTACODE VARCHAR(10),
ADDRESSTEXT VARCHAR(50)
CONSTRAINT  PK_ADDRESS PRIMARY KEY CLUSTERED(ID ASC))


