SELECT * FROM SALES ORDER BY AMOUNT

--SELECT COUNT(*) FROM SALES  --number of column

SELECT MIN(AMOUNT),MAX(AMOUNT) FROM SALES 

SELECT SUM(AMOUNT) FROM SALES 

SELECT AVG(AMOUNT) FROM SALES

SELECT  * FROM SALES ORDER BY TOTALPRICE 

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),SUM(TOTALPRICE), AVG(TOTALPRICE) FROM SALES 



SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),SUM(TOTALPRICE), AVG(TOTALPRICE) 
FROM SALES 
WHERE CITY='ADANA'

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),SUM(TOTALPRICE), AVG(TOTALPRICE) 
FROM SALES 
WHERE CITY='ANKARA'

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),SUM(TOTALPRICE), AVG(TOTALPRICE) 
FROM SALES 
WHERE CITY='ANKARA'
