SELECT MONTHNAME_,SUM(TOTALPRICE) AS TOTALPRICE 
FROM SALES
GROUP BY MONTHNAME_
ORDER BY MONTHNAME_


SELECT CITY,MONTHNAME_,SUM(TOTALPRICE) AS TOTALPRICE 
FROM SALES
GROUP BY CITY,MONTHNAME_
ORDER BY CITY,MONTHNAME_

