SELECT 
	ITM.CATEGORY1,
	SUM(OD.LINETOTAL) AS LINETOTAL,
	SUM(OD.AMOUNT) AS TOTALAMOUNT,
	COUNT(OD.ID) AS TOTALORDER

FROM ORDERS O
	INNER JOIN USERS U ON U.ID = O.USERID
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

WHERE ITM.CATEGORY1='EV'

GROUP BY  ITM.CATEGORY1
ORDER BY 2 DESC

-------------------------------------------------------


SELECT 
	ITM.CATEGORY1,ITM.CATEGORY2,
	SUM(OD.LINETOTAL) AS LINETOTAL,
	SUM(OD.AMOUNT) AS TOTALAMOUNT,
	COUNT(OD.ID) AS TOTALORDER

FROM ORDERS O
	INNER JOIN USERS U ON U.ID = O.USERID
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

WHERE ITM.CATEGORY1='EV'

GROUP BY  ITM.CATEGORY1,ITM.CATEGORY2
ORDER BY 3 DESC

----------------------------------------------------

SELECT 
	ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3,
	SUM(OD.LINETOTAL) AS LINETOTAL,
	SUM(OD.AMOUNT) AS TOTALAMOUNT,
	COUNT(OD.ID) AS TOTALORDER

FROM ORDERS O
	INNER JOIN USERS U ON U.ID = O.USERID
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

WHERE ITM.CATEGORY1='EV'

GROUP BY  ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3
ORDER BY 4 DESC

-------------------------------------------------------

SELECT 
	ITM.CATEGORY1,
	SUM(OD.LINETOTAL) AS LINETOTAL,
	SUM(OD.AMOUNT) AS TOTALAMOUNT,
	COUNT(OD.ID) AS TOTALORDER,
	SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) AS AVGUNITPRICE

FROM ORDERS O
	INNER JOIN USERS U ON U.ID = O.USERID
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

--WHERE ITM.CATEGORY1='EV'
GROUP BY  ITM.CATEGORY1
ORDER BY 5 DESC


