SELECT 
PAYMENTTYPE AS PAYMENTTYPE,
CASE 
	WHEN PAYMENTTYPE=1 THEN 'Credit Card'
	WHEN PAYMENTTYPE=2 THEN 'Bank Transfer'
END AS TYPE,

SUM(PAYMENTTOTAL) AS PAYMENTTOTAL
FROM PAYMENTS

GROUP BY PAYMENTTYPE

-------------------------------------------------
SELECT 
DATEPART(MONTH,DATE_) AS MONTH,
PAYMENTTYPE AS PAYMENTTYPE,
CASE 
	WHEN PAYMENTTYPE=1 THEN 'Credit Card'
	WHEN PAYMENTTYPE=2 THEN 'Bank Transfer'
END AS TYPE,

SUM(PAYMENTTOTAL) AS PAYMENTTOTAL
FROM PAYMENTS

GROUP BY PAYMENTTYPE ,DATEPART(MONTH,DATE_)
ORDER BY DATEPART(MONTH,DATE_)