SELECT 
TOP 10
CONVERT(DATE,O.DATE_) AS DATE,
SUM(OD.LINETOTAL) AS ORDERTOTALPRICE,
SUM(OD.AMOUNT) AS TOTALAMOUNT,
COUNT(OD.ID) AS TOTALORDERAMOUNT

FROM ORDERS O
	INNER JOIN USERS U ON U.ID = O.USERID
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

GROUP BY CONVERT(DATE,O.DATE_)
ORDER BY DATE


----------------------------------------------------

SELECT 
TOP 12
DATEPART(MONTH,O.DATE_) AS MONTH,
SUM(OD.LINETOTAL) AS ORDERTOTALPRICE,
SUM(OD.AMOUNT) AS TOTALAMOUNT,
COUNT(OD.ID) AS TOTALORDERAMOUNT

FROM ORDERS O
	INNER JOIN USERS U ON U.ID = O.USERID
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

GROUP BY DATEPART(MONTH,O.DATE_)
ORDER BY MONTH

-------------------------------------------------------------

SELECT 
TOP 12
DATEPART(YEAR,O.DATE_) AS YEAR,
SUM(OD.LINETOTAL) AS ORDERTOTALPRICE,
SUM(OD.AMOUNT) AS TOTALAMOUNT,
COUNT(OD.ID) AS TOTALORDERAMOUNT

FROM ORDERS O
	INNER JOIN USERS U ON U.ID = O.USERID
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

GROUP BY DATEPART(YEAR,O.DATE_)
ORDER BY YEAR

--------------------------------------------------------------

SELECT 
TOP 12
DATEPART(MONTH,O.DATE_) AS MONTH,
CASE 
	WHEN DATEPART(MONTH,O.DATE_)=1 THEN 'January'
	WHEN DATEPART(MONTH,O.DATE_)=2 THEN 'February'
	WHEN DATEPART(MONTH,O.DATE_)=3 THEN 'March'
	WHEN DATEPART(MONTH,O.DATE_)=4 THEN 'April'
	WHEN DATEPART(MONTH,O.DATE_)=5 THEN 'May'
	WHEN DATEPART(MONTH,O.DATE_)=6 THEN 'June'
	WHEN DATEPART(MONTH,O.DATE_)=7 THEN 'July'
	WHEN DATEPART(MONTH,O.DATE_)=8 THEN 'August'
	WHEN DATEPART(MONTH,O.DATE_)=9 THEN 'September'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'October'
	WHEN DATEPART(MONTH,O.DATE_)=11THEN 'November'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'December'
END AS MONTH_NAME,

SUM(OD.LINETOTAL) AS ORDERTOTALPRICE,
SUM(OD.AMOUNT) AS TOTALAMOUNT,
COUNT(OD.ID) AS TOTALORDERAMOUNT

FROM ORDERS O
	INNER JOIN USERS U ON U.ID = O.USERID
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

GROUP BY DATEPART(MONTH,O.DATE_)
ORDER BY MONTH
