SELECT * FROM SALES 
UPDATE SALES SET MONTHNAME_ = '01.January' WHERE DATEPART(MONTH,DATE2)=1
UPDATE SALES SET MONTHNAME_ = '02.February' WHERE DATEPART(MONTH,DATE2)=2
UPDATE SALES SET MONTHNAME_ = '03.March' WHERE DATEPART(MONTH,DATE2)=3
UPDATE SALES SET MONTHNAME_ = '04.April' WHERE DATEPART(MONTH,DATE2)=4
UPDATE SALES SET MONTHNAME_ = '05.May' WHERE DATEPART(MONTH,DATE2)=5
UPDATE SALES SET MONTHNAME_ = '06.June' WHERE DATEPART(MONTH,DATE2)=6
UPDATE SALES SET MONTHNAME_ = '07.July' WHERE DATEPART(MONTH,DATE2)=7
UPDATE SALES SET MONTHNAME_ = '08.August' WHERE DATEPART(MONTH,DATE2)=8
UPDATE SALES SET MONTHNAME_ = '09.September' WHERE DATEPART(MONTH,DATE2)=9
UPDATE SALES SET MONTHNAME_ = '10.October' WHERE DATEPART(MONTH,DATE2)=10
UPDATE SALES SET MONTHNAME_ = '11.November' WHERE DATEPART(MONTH,DATE2)=11
UPDATE SALES SET MONTHNAME_ = '12.December' WHERE DATEPART(MONTH,DATE2)=12


