# -*- coding: utf-8 -*-
"""filling_the _missing_values.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPX9ej6jXPiDkO8nQBH5scmuQNpzLrbf
"""

from sklearn.impute import SimpleImputer
import numpy as np

data = np.array([[1, 2, np.nan],
                 [4, np.nan, 6],
                 [7, 8, 9]])

# to fill the missing values in datasets
imputer = SimpleImputer(strategy='mean')

# Fit and transform data
imputed_data = imputer.fit_transform(data)

print(imputed_data)